<?php

namespace app\modules\register\controllers;

use app\modules\register\models\Registration;
use app\modules\register\models\RegistrationTeamMember;
use Yii;
use yii\web\Controller;

/**
 * Class DefaultController
 * @package app\modules\register\controllers
 */
class DefaultController extends Controller
{
    public $layout = '//blank';

    public function beforeAction($action)
    {
        $session = Yii::$app->session;
        $session->open();

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * @return string
     */
    public function actionStart()
    {
        $model =  new Registration();
        $primaryContact = $model->getPrimaryTeamMember();

        if (Yii::$app->request->isPost) {
            $model->load(Yii::$app->request->post());
            $primaryContact->load(Yii::$app->request->post());

            if ($model->validate() && $primaryContact->validate()) {
                $success = $model->save();

                $primaryContact->registration_id = $model->id;
                $primaryContact->save();

                for($i = 0; $i < $model->team_members; $i++) {
                    $contact = new RegistrationTeamMember();
                    $contact->registration_id = $model->id;
                    $contact->save(false);
                }

                $session = Yii::$app->session;
                $session->set('registration_id', $model->id);

                $this->redirect(['detail']);
            }
        }

        return $this->render(
            'start',
            [
                'model' => $model,
                'primaryContact' => $primaryContact,
            ]
        );
    }
    public function actionContinue()
    {
        if ($this->loadModel(false)) {
            $this->redirect(['detail']);
        }

        if (Yii::$app->request->isPost) {
            $email = Yii::$app->request->post('email');
            if ($email) {
                $teamMembers = RegistrationTeamMember::find()->where([
                    'primary_contact' => '1',
                    'email' => $email
                ])->all();
                if (count($teamMembers)) {
                    $mail = Yii::$app->mailer->compose(
                        [
                            'html' => 'register/send_link_html',
                            'text' => 'register/send_link_text',
                        ],
                        [
                            'teamMembers' => $teamMembers,
                        ]
                    )
                        ->setFrom(Yii::$app->params['fromEmail'])
                        ->setTo($teamMembers[0]->email)
                        ->setSubject('CBS 2016 - Continue Registration');
                    $mail->send();
                }
            }
        }

        return $this->render('continue');
    }
    public function actionDetail()
    {
        $model = $this->loadModel();
        $primaryContact = $model->getPrimaryTeamMember();

        return $this->render(
            'detail',
            [
                'model' => $model,
                'primaryContact' => $primaryContact,
            ]
        );
    }

    /**
     * @param bool $redirect
     * @return Registration
     */
    private function loadModel($redirect = true)
    {
        $session = Yii::$app->session;
        $registration_id = $session->get('registration_id');

        /* @var Registration $model */
        $model = Registration::findOne($registration_id);
        if (!$model && $redirect) {
            $this->redirect(['index']);
        }

        return $model;
    }

}
